// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmyldUmfF2cJlUMrqMghXyAK5ADjqznwQ',
    appId: '1:773457482523:android:bdd96ea1e9f2f2309579be',
    messagingSenderId: '773457482523',
    projectId: 'pokedex-9b4bf',
    storageBucket: 'pokedex-9b4bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6ZncW53d-lqIhdPSoK6C6T6R_7ICkek',
    appId: '1:773457482523:ios:b45c1a5269fe7e169579be',
    messagingSenderId: '773457482523',
    projectId: 'pokedex-9b4bf',
    storageBucket: 'pokedex-9b4bf.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu6ZncW53d-lqIhdPSoK6C6T6R_7ICkek',
    appId: '1:773457482523:ios:b45c1a5269fe7e169579be',
    messagingSenderId: '773457482523',
    projectId: 'pokedex-9b4bf',
    storageBucket: 'pokedex-9b4bf.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEJSY9WqoDOixNMNwmcbgSTVITZ7o9lQs',
    appId: '1:773457482523:web:d0d739782875558a9579be',
    messagingSenderId: '773457482523',
    projectId: 'pokedex-9b4bf',
    authDomain: 'pokedex-9b4bf.firebaseapp.com',
    storageBucket: 'pokedex-9b4bf.firebasestorage.app',
    measurementId: 'G-33PVX92Q6R',
  );
}
